### ISSUE TITLE
could not retrieve key

### ISSUE THREAD

**Issue by wbwangk** [nikfoundas/etcd-viewer#5]
I run etcd-viewer by docker. and use browser to request "127.0.0.1:8080", it display some errror:

Could not retrieve key /: javax.ws.rs.ProcessingException: java.net.ConnectException: ConnectException invoking http://localhost:2379/v2/keys/: Connection refused

**Comment by nikfoundas** [comment]
Hi @wbwangk ,

Since you are using the docker distribution the etcd registry is not accessible through the localhost (127.0.0.1) interface. You should configure your registry using the public ipv4 address of your registry. If your registry is located on your docker container host machine then you could either use the public ip address of your host machine or the ip of your docker bridge (I think by default this is 172.17.42.1).

Can you please verify this?

BR,
Nikos

**Comment by wbwangk** [comment]
thank @nikfoundas ,

i fixed this problem. i run etcd like this:   /bin/etcd -name etcdserver -data-dir /var/etcd -addr 10.10.56.2:4001 -bind-addr 0.0.0.0:4001 &

**Comment by nikfoundas** [comment]
Hi @wbwangk ,

So, I suppose we could close this issue. Would you agree?

Thanks!
